language: java

# Use JAva 1.8 for this project
jdk:
  - oraclejdk8

# setting install to true to avoid unnecessary build
install: true

before_install: echo "MAVEN_OPTS='-XX:-UseGCOverheadLimit'"

script: mvn clean install --settings settings.xml

after_success: mvn site deploy --settings settings.xml

branches:
  only:
    - develop

notifications:
  email:
    - info.uniknow@gmail.com